networks:
  default:
    name: "${INTERNAL_NETWORK}"

services:
  api:
    container_name: LibreChat
    ports:
      - "${LIC_PORT}:${LIC_PORT}"
    depends_on:
      - mongodb
      - rag_api
    image: "ghcr.io/danny-avila/librechat-api:${LIC_VERSION}"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - "${LIC_PATH_PREFIX}/conf/.env"
    environment:
      - HOST=0.0.0.0
      - PORT=${LIC_PORT}
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${LIC_RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${LIC_RAG_PORT:-8000}
    volumes:
      - type: bind
        source: 
        target: /app/.env
      - type: bind
        source: "${LIC_PATH_PREFIX}/conf/librechat.yaml"
        target: /app/librechat.yaml
      - ${LIC_PATH_PREFIX}/internal_data/images:/app/client/public/images
      - ${LIC_PATH_PREFIX}/internal_data/uploads:/app/uploads
      - ${LIC_PATH_PREFIX}/internal_data/logs:/app/logs
  mongodb:
    container_name: chat-mongodb
    image: mongo
    restart: always
    user: "${LIC_UID}:${LIC_GID}"
    volumes:
      - ${LIC_PATH_PREFIX}/mongo/data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: chat-meilisearch
    image: "getmeili/meilisearch:${LIC_MEILI_VERSION}"
    restart: always
    user: "${LIC_UID}:${LIC_GID}"
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${LIC_MEILI_MASTER_KEY}
    volumes:
      - ${LIC_PATH_PREFIX}/meili/meili_data_v1.12:/meili_data
  vectordb:
    container_name: vectordb
    image: "pgvector/pgvector:${LIC_VECTORDB_VERSION}"
    environment:
      POSTGRES_DB: ${LIC_DB_NAME}
      POSTGRES_USER: ${LIC_DB_USER}
      POSTGRES_PASSWORD: ${LIC_DB_PASS}
    restart: always
    volumes:
      - ${LIC_PATH_PREFIX}/vectordb/pgdata2:/var/lib/postgresql/data
  rag_api:
    container_name: rag_api
    image: "ghcr.io/danny-avila/librechat-rag-api-dev-lite:${LIC_RAG_VERSION}"
    environment:
      - DB_HOST=vectordb
      - POSTGRES_DB=${LIC_DB_NAME}
      - POSTGRES_USER=${LIC_DB_USER}
      - POSTGRES_PASSWORD=${LIC_DB_PASS}
      - RAG_PORT=${LIC_RAG_PORT:-8000}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env

