
networks:
  default:
    name: "${INTERNAL_NETWORK}"

services:
  registry:
    image: "registry:${DHUB_VERSION}"
    ports:
      - "${DHUB_PORT}:5000"
    restart: always
    volumes:
      - "./data/dhub/data:/var/lib/registry"
      - "./data/dhub/auth:/auth"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
