
networks:
  default:
    name: "${INTERNAL_NETWORK}"

services:
  miniflux:
    image: "miniflux/miniflux:${MINIFLUX_VERSION}"
    ports:
      - "${MINIFLUX_PORT}:8080"
    environment:
      - "DATABASE_URL=postgresql://${MINIFLUX_PSQL_USER}:${MINIFLUX_PSQL_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${MINIFLUX_PSQL_DB_NAME}"
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - "ADMIN_USERNAME=${MINIFLUX_A_USER}"
      - "ADMIN_PASSWORD=${MINIFLUX_A_PASSWORD}"

